name: Build and Publish LittleGames XamlResources NuGet Package

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install WinUI and MSIX build tools
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: msbuild LittleGamesXamlResources.sln /t:Restore /p:Configuration=Release

      # - name: Restore dependencies
      #   run: dotnet restore      

      - name: Build
        run: msbuild LittleGamesXamlResources.sln /p:Configuration=Release

      # - name: Build
      #   run: dotnet build --configuration Release

      - name: Pack NuGet package
        run: dotnet pack D:\a\LittleGamesXamlResources\LittleGamesXamlResources\LittleGamesXamlResources.csproj --configuration Release --output ./nupkgs

      - name: Push to GitHub Packages
        run: dotnet nuget push ./nupkgs/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}